#!/bin/sh
# launcher script for redeclipse_server

# location of binaries/data files
REDECLIPSE_PATH=/opt/redeclipse/

# location of maps/ and servinit.cfg
REDECLIPSE_HOME=/etc/redeclipse/

# name of the binary in $REDECLIPSE_PATH to run
REDECLIPSE_BINARY=redeclipse_server_linux

# disable auto updating
REDECLIPSE_BRANCH="inplace"

# additional options for keeping logs
#REDECLIPSE_OPTIONS="-g/var/log/redeclipse.log" #directly added to redeclipse.sh for now


. /opt/redeclipse/redeclipse_server.sh
